// TodoApp_Angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Todo } from './models/Todo';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  
  todos!:Todo[];
  inputText:string = "";
  filter:string = "all";

  constructor() { }

  ngOnInit(): void {
    this.getTodo();
  }

  async getTodo() {
    const res = await fetch('http://localhost:4000/api/todos');
    this.todos = await res.json();
  }

  async postTodo(todoText: string) {
    const res = await fetch(`http://localhost:4000/api/todos/`, {
      headers: { 'Content-Type': 'application/json' },
      method: 'POST',
      body: JSON.stringify({
				text: todoText,
				done: false 
			})
		});
		this.todos = await res.json();
    this.inputText = "";
  }

  async putTodo(todo: Todo) {
    const res =	await fetch(`http://localhost:4000/api/todos/${todo._id}`,
    {
			headers: { 'Content-Type': 'application/json' },
      method: 'PUT',
      body: JSON.stringify({
				text: todo.text,
				done: !todo.done
			})
    });
		this.todos = await res.json();
	}

  async deleteTodo(id: string) {
    const res = await fetch(`http://localhost:4000/api/todos/${id}`, 
    { 
      method: 'DELETE' 
    });
  this.todos = await res.json();
  }

  filterTodos(todos: Todo[], filter: string) {
    switch(filter) {
      case 'completed':
        return todos.filter((todo) => todo.done);
      case 'incomplete':
        return todos.filter((todo) => !todo.done);
      default: 
        return todos;
    }
  }

}

<!-- Startup -> ng serve -->
<div class="container">
  <header>TODO'er</header>
  <div class="todo">

    <div class="filters">
			<button (click)="this.filter = 'all'" class="{{ (filter === 'all' ? 'active' : '') }}">All</button>
			<button (click)="this.filter = 'completed'" class="{{ (filter === 'completed' ? 'active' : '') }}">Completed</button>
			<button (click)="this.filter = 'incomplete'" class="{{ (filter === 'incomplete' ? 'active' : '') }}">Incomplete</button>
		</div>

    <div class="form">
			<input 
        type="text" 
        placeholder="To do..."
        [(ngModel)]="inputText"
      />
			<button (click)="postTodo(inputText)" [disabled]="this.inputText.length === 0">Add</button>
		</div>

    <div class="tasks">

      <div class="task" *ngFor="let todo of filterTodos(todos, filter)">
        <div class="desc {{ (todo.done === true ? 'active' : '') }}">{{ todo.text }}</div>
        <div class="buttons">
          <button (click)="putTodo(todo)" class="{{ (todo.done === true ? 'active' : '') }}">
            <img src="../assets/check-circle.svg" alt="ok"/>
          </button>
          <button (click)="deleteTodo(todo._id)" class="todoTrashBtn">
            <img src="../assets/trash3-fill.svg" alt="x"/>
          </button>
        </div>
      </div>

    </div>
  </div>
</div>

// todoapp_react/src/App.js
import React, { useState, useEffect } from 'react';
import './App.css';
import FilterAndForm from './components/FilterAndForm';
import Todos from './components/Todos';

//Start app -> npm start

function App() {
  const [inputText, setInputText] = useState("");
  const [todos, setTodos] = useState([]);
  const [filter, setFilter] = useState("all");

  useEffect(() => {
    async function getTodo() {
      const res = await fetch('http://localhost:4000/api/todos');
      setTodos(await res.json());
    }
    getTodo();
	}, [])

	async function postTodo() {
		const res = await fetch(`http://localhost:4000/api/todos/`, {
			headers: { 'Content-Type': 'application/json' },
      method: 'POST',
      body: JSON.stringify({
				text: inputText,
				done: false 
			})
		})
		setTodos(await res.json());
	}

	async function putTodo(todo) {
	const res =	await fetch(`http://localhost:4000/api/todos/${todo._id}`,
    {
			headers: { 'Content-Type': 'application/json' },
      method: 'PUT',
      body: JSON.stringify({
				text: todo.text,
				done: !todo.done
			})
    })
		setTodos(await res.json());
	}

	async function deleteTodo(id) {
		const res = await fetch(`http://localhost:4000/api/todos/${id}`, 
			{ 
				method: 'DELETE' 
			})
      setTodos(await res.json());
	}

  return (
    <div className="container">
      <header>TODO'er</header>
      <div className="todo">
        <FilterAndForm 
          todos={todos} 
          setTodos={setTodos} 
          inputText={inputText} 
          setInputText={setInputText}
          postTodo={postTodo}
          filter={filter}
          setFilter={setFilter}
        />
        <Todos 
          todos={todos} 
          setTodos={setTodos}
          deleteTodo={deleteTodo}
          putTodo={putTodo}
          filter={filter}
        />
      </div>
  </div>
  );
}

export default App;
